### ISSUE TITLE
Checks with confine block should explain why it had failed

### ISSUE THREAD

**Issue by swapab** [iNecas/foreman_maintain#11]
Confine block such as following, would fail if any of the packages is not installed. There is no explanation in such cases. IMO the check should either FAIL with a message OR just `say` the reason for check failure.

```ruby
  confine do
    execute?('which hdparm') && execute?('which fio')
  end
```

**Comment by iNecas** [comment]
If we want to fail, it should not be in confine bloc, but part of the check itself.

**Comment by iNecas** [comment]
For this particular case, the ideal solution would be to offer to install the tools

**Comment by iNecas** [comment]
Another altentative would be for definitios to be able to define additional packages they need to install, and we could collect this packages at the beginning and offer them to install those before continuing.

We could also solve this on packaging level, but I think for our purposes, it would be easier just to offer to install those: this way, the tool can stay lightweight enough (not requiring additional packages to be installed before starting to use this, as only a subset of functionality needs it).

**Comment by swapab** [comment]
> For this particular case, the ideal solution would be to offer to install the tools

This was just an example I thought of where confine block failed and I was having no idea why the check didn't execute(until I realized a package was missing). Another example I can think of is [foreman_database.rb](https://github.com/iNecas/foreman_maintain/blob/master/definitions/features/foreman_database.rb#L4-L6) consider this as a check, where let's say the file doesn't exist. In this case, the check won't execute and just move ahead without any explanation.

> We could also solve this on packaging level, but I think for our purposes, it would be easier just to offer to install those: this way, the tool can stay lightweight enough (not requiring additional packages to be installed before starting to use this, as only a subset of functionality needs it).

+1, totally agree with this approach, rather than requiring the tools we can pre-check their existence and offer to install them beforehand. Shall we create an issue for this?

**Comment by iNecas** [comment]
For the foreman_database. this is different: we use confine there, because if you run on capsule, we don't expect the foreman to be present at all.

**Comment by iNecas** [comment]
Please go ahead and create an issue for that.

**Comment by swapab** [comment]
> For the foreman_database. this is different: we use confine there, because if you run on capsule, we don't expect the foreman to be present at all.

Okay. That makes me think I misinterpreted `confine` :)
So it's basically **restricting** an execution and _not validating_.

**Comment by iNecas** [comment]
Exactly.
