### ISSUE TITLE
Offer to delete the tasks that are not valid any more

### ISSUE THREAD

**Issue by swapab** [iNecas/foreman_maintain#16]

**Comment by swapab** [comment]
@iNecas 
* Delete all tasks in planning state
  Q. Shall we delete **all** tasks those are in planning state or should restrict to certain date/type of tasks?

 * Delete all tasks in pending state that are safe to delete
  Q1. Same as above
  Q2. How can be best define 'safe to delete' tasks?

**Comment by iNecas** [comment]
This is more a question for @mccun934, I would recommand, I would rather got with a smaller set, that can happen often, such as `Actions::Katello::Repository::Sync` and perhaps `Actions::Candlepin::ListenOnCandlepinEvents` and widen the range as we go.

**Comment by swapab** [comment]
Closed #33
