### ISSUE TITLE
How to: persistence test - test SQL queries

### ISSUE THREAD

**Issue by swapab** [iNecas/foreman_maintain#32]
Take inspiration from dF? https://github.com/Dynflow/dynflow/blob/master/test/persistence_test.rb

Or maybe something simpler where we can mimic `katello/foreman` database into the `test` environment, pump in data and query accordingly.

**Comment by iNecas** [comment]
I think we should rely on system testing here, perhaps QEs could help us with this kind of testing

**Comment by swapab** [comment]
I usually prefer to test everything(almost) within the library. If we could setup some a test ORM or something similar to that which would create persisting data or fake it.
This is just good to have. We can put it in the exceptional bucket for now.

**Comment by swapab** [comment]
As I think of it, features should not be tested in library automation test suite. No reason to keep it open.
#closing
