### ISSUE TITLE
Change 'basic' tag to 'default' : command `health check`

### ISSUE THREAD

**Issue by swapab** [iNecas/foreman_maintain#44]
@iNecas If I remember, we had a discussion about changing the default tag for `health check` command from **basic** to **pre_upgrade**.
If this holds true, I'll send a PR against this issue.

Following is health check list:
```bsah
sat62 :: ~/foreman_maintain ‹master*› » ./bin/foreman-maintain health list
[disk-io] Check for recommended disk speed of pulp, mongodb, pgsql dir. [basic]
[foreman-tasks-not-paused] check for paused tasks                       [basic]
[foreman-tasks-not-running] check for running tasks                     [pre-upgrade]
```

Right now only 1 check with pre-upgrade tag, should we assign rest of the checks to `pre-upgrade` tag?

**Comment by iNecas** [comment]
I'm more thinking about the `basic` as ones, that are valid both for upgrades, as well as day to day, while the pre-upgrade ones only for the upgrade phase. In this regards, I could think about disk speed check more as a pre-upgrade, the same for running tasks, but the paused ones should remain basic. Btw. I'm thinking renaming `basic` tag, to `default`, as it probably describes a bit better the behavior

**Comment by swapab** [comment]
Agreed.
1. Rename tag `basic` to `default`.
2. Disk speed check to be tagged as `pre-upgrade`.
3. Default tag in action for health check command will be `default`.

**Comment by iNecas** [comment]
ACK
