### ISSUE TITLE
Cannot setup foreman_maintain, complains about foreman-maintain-hammer.yml not found

### ISSUE THREAD

**Issue by san7ket** [iNecas/foreman_maintain#59]
Looking at the https://github.com/iNecas/foreman_maintain/tree/master/config , I can see just two config files  foreman_maintain.yml.example,hammer.yml.example.
When i run the foreman-maintain have the setting configured
```

./foreman-maintain health check
 
Running checks with tags [default]
================================================================================
check for paused tasks:                                               [FAIL]
There are currently 2 paused tasks in the system
--------------------------------------------------------------------------------
There are multiple steps to proceed:
1) resume paused tasks
2) investigate the tasks via UI
Select step to continue, [n(next), q(quit)] 1
resume paused tasks:                                                  [OK]
Error: Custom configuration file /root/foreman_maintain/config/foreman-maintain-hammer.yml does not exist.
--------------------------------------------------------------------------------
Rerunning the check after fix procedure
check for paused tasks:                                               [FAIL]
There are currently 2 paused tasks in the system
```

Am I missing something?

**Comment by kgaikwad** [comment]
@san7ket,

This error is related to hammer config file which is used to trigger hammer commands.
This file is created in preparation steps of any of the check first time.

Currently, this preparation step is absent for resume paused tasks check. 
While triggering hammer command for this check 'resume paused task',
you are getting above error. We are working on it.

For now, could you please try to run -  `.bin/foreman-maintain upgrade check `
which will ask you to enter hammer credentials first time.
Then again run `.bin/foreman-maintain health check`  and check the output.

Please let me know if you are still facing the same issue.
